site_name: LF8-ItSystemhaus-Software
nav:
  - index.md
  - deployment_mit_mkdocs.md
  - phase5.md
  - phase6.md
  - phase7.md
  - phase8.md
  - phase9.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
